# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resources/pop_up_error_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(333, 162)
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 19, 311, 131))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.errorGridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.errorGridLayout.setContentsMargins(0, 0, 0, 0)
        self.errorGridLayout.setObjectName("errorGridLayout")
        self.errorCloseButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.errorCloseButton.setObjectName("errorCloseButton")
        self.errorGridLayout.addWidget(self.errorCloseButton, 1, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.errorGridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.errorLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.errorLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.errorLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.errorLabel.setObjectName("errorLabel")
        self.errorGridLayout.addWidget(self.errorLabel, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.errorGridLayout.addItem(spacerItem1, 1, 2, 1, 1)

        self.retranslateUi(Form)
        self.errorCloseButton.clicked.connect(Form.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.errorCloseButton.setText(_translate("Form", "Close"))
        self.errorLabel.setText(_translate("Form", "Error: Only numbers allowed"))
